"""
Alert Model
Stores alerts and warnings generated by the system
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, Enum
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum
from database.connection import Base

class AlertSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"

class AlertType(str, enum.Enum):
    ANOMALY_DETECTED = "anomaly_detected"
    FAULT_PREDICTED = "fault_predicted"
    MAINTENANCE_DUE = "maintenance_due"
    TEMPERATURE_HIGH = "temperature_high"
    VIBRATION_HIGH = "vibration_high"
    SUPPLY_CHAIN_RISK = "supply_chain_risk"
    INVENTORY_LOW = "inventory_low"

class AlertStatus(str, enum.Enum):
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"

class Alert(Base):
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    machine_id = Column(Integer, ForeignKey("machines.id"), nullable=True, index=True)
    
    alert_type = Column(Enum(AlertType), nullable=False)
    severity = Column(Enum(AlertSeverity), nullable=False, default=AlertSeverity.WARNING)
    status = Column(Enum(AlertStatus), default=AlertStatus.ACTIVE)
    
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    
    # Prediction data
    fault_probability = Column(Float, nullable=True)  # 0-100
    predicted_failure_window = Column(String(50), nullable=True)  # e.g., "24-48 hours"
    anomaly_score = Column(Float, nullable=True)
    
    # Metadata
    acknowledged_by = Column(String(100), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    
    # Relationships
    machine = relationship("Machine", back_populates="alerts")
    
    def __repr__(self):
        return f"<Alert(id={self.id}, type='{self.alert_type}', severity='{self.severity}')>"











